spring:
  application:
    name: springdataredis_demo

  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    database: 0  #redis会默认为我们提供16个数据库，这里的0表示使用0号数据库
    jedis:
      pool:
        #Redis.连接池配置
        max-active: 8 #最大链接数
        max-wait: 1ms #连接池的最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
